const mockProducts = [
    {
        name: "Classic T-Shirt",
        desc: "A timeless cotton t-shirt for everyday wear",
        price: 19.99,
        img: "/images/products/classic-tshirt.jpeg",
        available: true,
        remaining: 150,
        discount: 0.0,
        color: "White",
        size: "M",
        sku: "TSHIRT-001",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        name: "Slim Fit Jeans",
        desc: "Comfortable slim-fit denim jeans",
        price: 49.99,
        img: "/images/products/slim-fit-jeans.jpeg",
        available: true,
        remaining: 80,
        discount: 5.0,
        color: "Blue",
        size: "L",
        sku: "JEANS-001",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        name: "Hooded Sweatshirt",
        desc: "Warm hoodie for casual outings",
        price: 39.99,
        img: "/images/products/hooded-sweatshirt.jpeg",
        available: true,
        remaining: 120,
        discount: 10.0,
        color: "Gray",
        size: "XL",
        sku: "HOODIE-001",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        name: "Running Sneakers",
        desc: "Lightweight sneakers for everyday running",
        price: 69.99,
        img: "/images/products/running-sneakers.jpeg",
        available: true,
        remaining: 60,
        discount: 0.0,
        color: "Black",
        size: "M",
        sku: "SNEAKERS-001",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        name: "Leather Jacket",
        desc: "Stylish leather jacket for winter",
        price: 149.99,
        img: "/images/products/stylish-leather-jacket.jpeg",
        available: true,
        remaining: 30,
        discount: 15.0,
        color: "Brown",
        size: "L",
        sku: "JACKET-001",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        name: "Casual Shorts",
        desc: "Comfortable summer shorts",
        price: 29.99,
        img: "/images/products/comfortable-summer-shorts.jpeg",
        available: true,
        remaining: 200,
        discount: 0.0,
        color: "Khaki",
        size: "M",
        sku: "SHORTS-001",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        name: "Graphic T-Shirt",
        desc: "Cotton T-shirt with printed graphics",
        price: 24.99,
        img: "/images/products/cotton-tshirt-with-printed-graphics.jpeg",
        available: true,
        remaining: 100,
        discount: 5.0,
        color: "Black",
        size: "S",
        sku: "TSHIRT-002",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        name: "Denim Jacket",
        desc: "Classic blue denim jacket",
        price: 89.99,
        img: "/images/products/classic-blue-denim-jacket.jpeg",
        available: true,
        remaining: 45,
        discount: 10.0,
        color: "Blue",
        size: "XL",
        sku: "JACKET-002",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        name: "Yoga Pants",
        desc: "Stretchable pants for workouts",
        price: 34.99,
        img: "/images/products/stretchable-pants-workouts.jpeg",
        available: true,
        remaining: 70,
        discount: 0.0,
        color: "Gray",
        size: "L",
        sku: "PANTS-001",
        createdAt: new Date(),
        updatedAt: new Date()
    },
    {
        name: "Windbreaker Jacket",
        desc: "Lightweight windbreaker for running",
        price: 59.99,
        img: "/images/products/lightweight-windbreaker.jpeg",
        available: true,
        remaining: 50,
        discount: 5.0,
        color: "Red",
        size: "M",
        sku: "JACKET-003",
        createdAt: new Date(),
        updatedAt: new Date()
    }
];

module.exports = mockProducts;
